### ISSUE TITLE
[Question] Is it safe to erase while executing overlap_find_all?

### ISSUE THREAD

**Issue by m-carrasco** [5cript/interval-tree#15]
Hi,

Before all, thanks a lot for sharing this code!

I just wanted to ask if the following is safe to do:

```
    tree.overlap_find_all(newInterval,
    [&](auto iter) {

        if (newInterval.within(*iter) /* or any other condition */){
            // is it safe to erase while overlap_find_all iterates over the structure?
            newInterval.erase(iter);
        }

        return true;
    }, 
    false);
```
Best regards,
Manuel.

**Comment by 5cript** [comment]
Its not safe. Especially when erase causes restructuring of the rbtree. I currently dont have a quick answer on achievieng this performantly.

**Comment by m-carrasco** [comment]
Thanks for your answer @5cript 

Regardless of performance, to be safe, `find` and `erase` should be called one at a time until no more elements meet the criteria. Do you agree?

**Comment by 5cript** [comment]
@m-carrasco 
The tree could use a filter method to make it work. But I am a little overworked atm.
But yes, unfortunately you can only do this by iterating normally and use the returned iterator of erase. This does not have the benefit of using the max property to avoid search down subtrees that cannot possibly have overlaps.

**Comment by 5cript** [comment]
> I have one last question, which probably is better in a new issue. As far as I understand, each interval does not hold a value as if it were a container. In other words, the current state of the interval tree cannot be used as a map from intervals to values of type T. Do you agree?
> 
> Again, thanks a lot for your answers and for sharing this project.

One could make an interval type though, that does satisfy the "interface" the tree class expects.
You could safely derive from it (as long as you do not use it polymorphically, since no virt destructor exists (yet?)) and extend it with data as you need it.
