### ISSUE TITLE
test FailBadBorders fails

### ISSUE THREAD

**Issue by pkovacs** [5cript/interval-tree#16]
```
$ ./tree-tests
...
[==========] 69 tests from 9 test suites ran. (383 ms total)
[  PASSED  ] 68 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IntervalTests.FailBadBorders

 1 FAILED TEST
```

```
$ g++ --version
g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

$ arch
x86_64
```

**Comment by pkovacs** [comment]
Looks like the problem is simply that `assert` only fails that test for debug builds.  Also note that `-fexceptions` is spelled wrong.

```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index a66e9b7..133aeab 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -37,3 +37,3 @@ endif()
 # Compiler Options
-set(DEBUG_OPTIONS -fexecptions -g -Wall -pedantic-errors -pedantic)
+set(DEBUG_OPTIONS -fexceptions -g -Wall -pedantic-errors -pedantic)
 target_compile_options(tree-tests PUBLIC "$<$<CONFIG:DEBUG>:${DEBUG_OPTIONS}>")
```

**Comment by 5cript** [comment]
I will take a look at it.

**Comment by 5cript** [comment]
I will change that to an exception

**Comment by 5cript** [comment]
I will use this as an opportunity to do a cleanup of the project structure, moving all files to a new include directory and providing a cmake INTERFACE library. Also moving the drawings out of the tests, where it does not belong and cleaning that up.

**Comment by 5cript** [comment]
This issue is resolved. If you want to locally verify, you now need to to build from the top level directory, no longer the tests directory.
