### ISSUE TITLE
cmake and cxx requirements are too strict

### ISSUE THREAD

**Issue by pkovacs** [5cript/interval-tree#17]
1. You bumped the cmake requirement up to 3.21 which is too high and unnecessary -- you can harmlessly lower this, e.g. to 3.14.
2. You require CXX 14 for generic lambdas such as `[](auto const& lhs, auto const& rhs){}`.  Would be nice to allow CXX 11 also, for maximum compatibility.   Try building with `cmake -DCMAKE_CXX_STANDARD=11 ..`

**Comment by 5cript** [comment]
I have removed my use of PROJECT_IS_TOP_LEVEL to revert the cmake version, but I am not going to enable support C++11. You may open a PR to fix this, but I won't guarantee to break that in the future.

**Comment by 5cript** [comment]
I will close this issue for now.
