### ISSUE TITLE
Will implementation of overlapping of different interval kinds be added in future updates?

### ISSUE THREAD

**Issue by CrSjimo** [5cript/interval-tree#34]
Related issue: #8 

I've noticed that this project was recently updated to a new major version. I am looking forward to the overlapping detection for left-closed-right-open (and other kinds of) intervals. Will this feature be added in the future?

**Comment by 5cript** [comment]
I assume this includes inserting different kinds of intervals into the tree, some closed some open etc.
I am investigating a good way of doing this. It should be already possible by creating your own interval class that implements your own overlap function. But I can provide this in-library.

**Comment by 5cript** [comment]
This actually gets ugly for floats. I dont think I will provide an interval out of the box for floating point borders, when they arent the same type (closed/open).

There is also an ambiguity for integral types.
(3, 5] overlap [2, 5] could be both (3, 5] and [2, 5].

**Comment by 5cript** [comment]
The interval method `bool overlaps(value_type l, value_type h) const` will be deprecated after this.
Because this method makes the interval information for the interval that (l, h) belongs to invisible.
Old behavior is to assume closed for everything.

**Comment by 5cript** [comment]
https://github.com/5cript/interval-tree/releases/tag/v2.3.0
