### ISSUE TITLE
associate some value with interval

### ISSUE THREAD

**Issue by redplait** [5cript/interval-tree#41]
hello
is it possible to associate some template value with interval?
like
```c++
interval_tree<interval<int, closed>, TValue> tree;
tree.insert({}, TValue);
auto in_tree = tree.overlap_find( {} );
if ( in_tree != tree.end() ) { in_tree.value }
```

**Comment by 5cript** [comment]
You can inherit from interval<T, Type> and add a value to it.
TValue must be copy and moveable.

**Comment by redplait** [comment]
then method interval::join should be virtual to allow joining of two TValue?

**Comment by 5cript** [comment]
you can shadow it. Redeclare the function without overriding. The interval class is never used polymorphically.
You could also not override it, if it returns a different non reference interface class, because it has a different signature.

**Comment by 5cript** [comment]
I added a super basic test for this scenario.

```c++
struct minimal_custom_interval : public lib_interval_tree::interval<int, lib_interval_tree::closed>
{
    using lib_interval_tree::interval<int, lib_interval_tree::closed>::interval;

    minimal_custom_interval join(minimal_custom_interval const& other) const
    {
        std::cout << "I am called here!";
        return {std::min(low_, other.low_), std::max(high_, other.high_)};
    }
};
```

**Comment by 5cript** [comment]
I consider this resolved, reopen if further discussion is needed.
