### ISSUE TITLE
Question: how to find all intervals, for example, intersecting ones?

### ISSUE THREAD

**Issue by Shempp** [5cript/interval-tree#6]
`interval_tree_t` has methods, such as` overlap_find` and `overlap_find_next`. But how to use them to find all occurrences? Does the library support this functionality?

**Comment by 5cript** [comment]
you can use find and find_next to find exact matches. Sorry for the late response.
```c++
for (auto begin = tree.find({23, 132}); begin != tree.end(); begin = tree.find_next(begin, {23, 132}))
{
}
```
Same with overlap find.

**Comment by Shempp** [comment]
Greetings and thanks for your reply. Yes, I tried the option you already presented, but my iterator does not shift - is it a bug? Sample code:
```
    using namespace lib_interval_tree;

    interval_tree_t <int> tree;

    tree.insert({ 0, 5 });
    tree.insert({ 5, 10 });
    tree.insert({ 10, 15 });
    tree.insert({ 15, 20 });

    for (auto iter = tree.overlap_find({ 5, 5 }); iter != tree.end(); iter = tree.overlap_find_next(iter, { 5, 5 })) {
        std::cout << (*iter).low() << " " << (*iter).high() << std::endl;
    }
```

Output:
5 10
5 10
5 10
And so on (endless loop).

**Comment by 5cript** [comment]
Yes thats a bug. I would expect (0, 5)->(5, 10)->end.
Hmmm, I will have to take a look at this.

**Comment by 5cript** [comment]
Ah i see. The functions are just very confusing. find_next INCLUDES the iterator given to it, but since I did the same mistake as you, I think the interface is wrong, because irritating.
I will change it so that your example will work.

Also nodes now have a low() and high() method, so you can write `iter->low()`.
Thanks  for this report.

**Comment by 5cript** [comment]
I will have to add a find_all / overlap_find_all method.
The find next can never work. I renamed them and thinking about removing them altogether maybe.
Because the find state is not preserved over calls, going back up in the tree is impossible.

**Comment by 5cript** [comment]
I have added (overlap_)find_all functions and documented them.
Waiting for feedback.

**Comment by Shempp** [comment]
Yeah, now it work. Thank you!
